name: struct NL 2026
title: null #"<strong>Home</strong>"
description: Utrecht University - June 18-19, 2026
baseurl: Struct-NL-2026/
url: https://ndns-struct-nl.github.io/struct-nl-2026

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: NDNS+
indexing: true

favicon_ico: "/assets/icons/favicon.ico"

navbar:
  - title: Home    # <-- Add this block
    url: /
  - title: Program
    url: /program/
  - title: Participants
    url: /participants/

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
