title: Struct-NL 2026
description: Utrecht Univeristy -- June 18-19, 2026
baseurl: Struct-NL-2026/
url: https://ndns-struct-nl.github.io/struct-nl-2026

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: NDNS+
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
